- name: This Ansible Playbook will deploy nginx application into OpenShift Cluster
  hosts: localhost
  tasks:

  - name: Create a k8s namespace
    k8s:
      name: tektutor
      api_version: v1
      kind: Namespace
      state: present

  - name: Create a nginx deployment inline 
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: tektutor
          labels:
            app: nginx
            ver: "1.23"
          name: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - image: bitnami/nginx:1.23
                name: nginx

  - name: Create a nginx clusterip service
    k8s:
      state: present
      src: ../../Day3/manifests/nginx-clusterip-svc.yml

  - name: Create a nginx public route
    k8s:
      state: present
      src: ../../Day3/manifests/nginx-route.yml